'use client';

import { useCallback, useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowLeft, ArrowRight, Plus, X, CalendarDays, RefreshCw, AlertTriangle, History, Users, Check, ChevronDown, SlidersHorizontal, Pencil, ArrowUpRight } from 'lucide-react';
import { WeekStrip, MonthCalendar } from './schedule-calendar';
import { shiftMonth } from '@/lib/calendar';
import { DEMO_NOW, INITIAL_DATE, TIMEZONE, type ApiError, type Booking, type ScheduleChange, type ScheduleData, type Session, type SessionInput, type Warning } from '@/lib/contracts';

const formatDay = (date: string) => new Date(`${date}T12:00:00`).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
const weekday = (date: string) => new Date(`${date}T12:00:00`).toLocaleDateString('en-GB', { weekday: 'long' });
const endTime = (s: Session) => { const [h, m] = s.startTime.split(':').map(Number); const t = h * 60 + m + s.durationMin; return `${String(Math.floor(t / 60)).padStart(2, '0')}:${String(t % 60).padStart(2, '0')}`; };
const moveDay = (date: string, delta: number) => { const d = new Date(`${date}T12:00:00Z`); d.setUTCDate(d.getUTCDate() + delta); return d.toISOString().slice(0, 10); };
const statusLabel = (status: string) => status === 'no_show' ? 'No-show' : status === 'cancelled' ? 'Cancelled' : 'Booked';
function Status({ status }: { status: string }) { return <span className={`badge status-${status}`}>{status === 'booked' && <span className="status-dot" />}{statusLabel(status)}</span>; }
function Warnings({ warnings }: { warnings: Warning[] }) { return warnings.length ? <details className="warning-details"><summary><AlertTriangle size={14} /> {warnings.length === 1 ? warnings[0].code.toLowerCase().replaceAll('_', ' ') : `${warnings.length} existing issues`}<ChevronDown size={12} /></summary><div className="warning-copy">{warnings.map((w, i) => <p key={i}>{w.message}{w.sourceLessonIds.length > 0 && <small>Source: {w.sourceLessonIds.join(', ')}</small>}</p>)}</div></details> : <span className="no-issues">—</span>; }
function Snapshot({ session }: { session: Session | null }) { return session ? <div className="snapshot"><strong>{formatDay(session.date)} · {session.startTime}–{endTime(session)}</strong><span>{session.tutorName} · {session.roomId}</span>{session.bookings.map(b => <span key={b.id}>{b.studentName} · {statusLabel(b.status)}</span>)}</div> : <span className="muted">No previous session</span>; }
function Change({ change, date }: { change: ScheduleChange; date: string }) { const moved = change.before && change.before.date !== change.after.date; return <article className="change"><div className="change-heading"><strong>{moved ? change.before?.date === date ? `Moved to ${formatDay(change.after.date)}` : `Moved from ${formatDay(change.before!.date)}` : change.action === 'created' ? 'Session created' : change.action === 'cancelled' ? 'Booking cancelled' : 'Session updated'}</strong>{change.afterCutoff && <span className="badge warning-badge" title="Changed after the schedule cutoff; notification is not confirmed.">After cutoff</span>}<time>{new Date(change.occurredAt).toLocaleString('en-GB', { timeZone: TIMEZONE, day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit', hour12: false })}</time></div>{change.reason && <p>{change.reason}</p>}<details><summary>View before and after</summary><div className="snapshot-grid"><div><span className="eyebrow">Before</span><Snapshot session={change.before} /></div><div><span className="eyebrow">After</span><Snapshot session={change.after} /></div></div></details></article>; }

export function SchedulingBoard() {
  const [date, setDate] = useState(INITIAL_DATE);
  const [view, setView] = useState<'week' | 'month'>('week');
  const [calendarRevision, setCalendarRevision] = useState(0);
  const [data, setData] = useState<ScheduleData | null>(null);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState('');
  const [notice, setNotice] = useState('');
  const [tutor, setTutor] = useState('');
  const [student, setStudent] = useState('');
  const [editor, setEditor] = useState<{ session?: Session } | null>(null);
  const [cancelling, setCancelling] = useState<{ session: Session; booking: Booking } | null>(null);
  const request = useRef(0);
  const reload = useCallback(async (targetDate = date) => {
    const token = ++request.current; setLoading(true); setLoadError('');
    try { const response = await fetch(`/api/schedule?date=${targetDate}`, { cache: 'no-store' }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Unable to load the schedule.'); if (token === request.current) { setData(payload); if (targetDate !== date) setDate(targetDate); } return true; }
    catch (error) { if (token === request.current) setLoadError(error instanceof Error ? error.message : 'Unable to load the schedule.'); return false; }
    finally { if (token === request.current) setLoading(false); }
  }, [date]);
  useEffect(() => { setData(null); void reload(); return () => { request.current++; }; }, [reload]);
  const saved = async () => { setEditor(null); setCancelling(null); setNotice('Changes saved.'); setCalendarRevision(value => value + 1); if (!(await reload())) setNotice('Saved successfully, but the schedule could not refresh. Reload before making another change.'); };
  const visible = data?.sessions.filter(s => (!tutor || s.tutorId === tutor) && (!student || s.bookings.some(b => b.studentId === student))) ?? [];
  const issues = data?.warnings.length ?? 0;
  const activeCount = data?.sessions.reduce((count, s) => count + s.bookings.filter(b => b.status !== 'cancelled').length, 0) ?? 0;
  const canWrite = !!data && !loading && !loadError;
  const editButton = (s: Session) => { const blocked = s.bookings.every(b => b.status === 'cancelled') || s.bookings.some(b => b.status === 'no_show'); return <button className="button ghost edit-button" disabled={!canWrite || blocked} title={blocked ? 'Cancelled or no-show sessions cannot be rescheduled.' : 'Edit the whole session'} onClick={() => setEditor({ session: s })}><Pencil size={14} />Edit</button>; };
  const students = (s: Session) => <div className="students">{s.mode === 'pair' && <span className="badge pair"><Users size={12} />Pair session</span>}{s.bookings.map(b => <div className="student-entry" key={b.id}><div className="student-name">{b.studentName}{s.mode === 'pair' && <Status status={b.status} />}</div>{b.status !== 'cancelled' && <button className="text-button cancel-link" disabled={!canWrite} aria-label={`Cancel booking for ${b.studentName}`} onClick={() => setCancelling({ session: s, booking: b })}>Cancel booking</button>}<details className="booking-details"><summary>Booking details</summary><div>{b.sourceLessonId && <p>Source: {b.sourceLessonId}</p>}{b.sourceNote && <p>{b.sourceNote}</p>}{b.cancelledAt && <p>Cancelled: {new Date(b.cancelledAt).toLocaleString('en-GB', { timeZone: TIMEZONE })}</p>}{b.reason && <p>Reason: {b.reason}</p>}<p>Booking: {b.id}</p></div></details></div>)}</div>;
  return <><header className="site-header"><div className="header-inner"><a className="brand" href="/" aria-label="Bright Path home"><span className="brand-mark"><span /></span><span>bright path<span className="brand-caption">LEARNING CENTRE</span></span></a><details className="demo-info"><summary>Demo</summary><div><p>Sample data</p><p>Today: {new Date(DEMO_NOW).toLocaleString('en-GB', { timeZone: TIMEZONE, day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit', hour12: false })} · UTC+7</p></div></details></div></header>
    <main className="workspace">
      <section className="day-heading"><div><p className="eyebrow">SCHEDULE</p><h1>{view === 'month' ? new Date(`${date}T12:00:00Z`).toLocaleDateString('en-GB', { month: 'long', year: 'numeric', timeZone: 'UTC' }) : formatDay(date)}</h1>{view === 'week' && <p className="date-subtitle">{weekday(date)}</p>}</div><button className="button primary add-button" disabled={!canWrite} onClick={() => setEditor({})}><Plus size={18} />Add session</button></section>
      <section className="board" aria-label="Daily schedule"><div className="board-toolbar"><div className="date-controls"><div className="nav-group"><button className="button icon" aria-label={view === 'week' ? 'Previous week' : 'Previous month'} onClick={() => setDate(view === 'week' ? moveDay(date, -7) : shiftMonth(date, -1))}><ArrowLeft size={17} /></button><button className="button today" onClick={() => setDate(DEMO_NOW.slice(0, 10))}>Today</button><button className="button icon" aria-label={view === 'week' ? 'Next week' : 'Next month'} onClick={() => setDate(view === 'week' ? moveDay(date, 7) : shiftMonth(date, 1))}><ArrowRight size={17} /></button></div><label className="date-input"><CalendarDays size={16} /><input aria-label="View date" type="date" value={date} onChange={e => e.target.value && setDate(e.target.value)} /></label></div><div className="schedule-totals"><div className="view-switch" role="group" aria-label="Calendar view">{(['week', 'month'] as const).map(mode => <button key={mode} type="button" aria-pressed={view === mode} onClick={() => setView(mode)}>{mode === 'week' ? 'Week' : 'Month'}</button>)}</div>{view === 'week' && <><span><strong>{data?.sessions.length ?? '—'}</strong> sessions</span><span><strong>{data ? activeCount : '—'}</strong> active bookings</span></>}<button className="button icon refresh" aria-label="Refresh schedule" disabled={loading} onClick={() => { setNotice(''); setCalendarRevision(value => value + 1); void reload(); }}><RefreshCw size={16} className={loading ? 'spin' : ''} /></button></div></div>
        {view === 'week' && <WeekStrip date={date} onSelect={setDate} />}
        <div className="filter-toolbar"><div className="filter-label"><SlidersHorizontal size={15} />Filter</div><label className="filter-select"><span className="sr-only">Filter by tutor</span><select value={tutor} onChange={e => setTutor(e.target.value)}><option value="">All tutors</option>{data?.tutors.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="filter-select"><span className="sr-only">Filter by student</span><select value={student} onChange={e => setStudent(e.target.value)}><option value="">All students</option>{data?.students.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{(tutor || student) && <button className="text-button" onClick={() => { setTutor(''); setStudent(''); }}>Clear filters</button>}{view === 'week' && (tutor || student) && <span className="visible-count">{visible.length} of {data?.sessions.length ?? 0} sessions</span>}</div>
        {notice && <div role="status" className="notice"><Check size={16} />{notice}<button className="button icon" aria-label="Dismiss notification" onClick={() => setNotice('')}><X size={15} /></button></div>}
        {loadError && <div role="alert" className="error-banner"><AlertTriangle size={18} /><div><strong>Schedule unavailable</strong><p>{loadError}</p><button className="text-button" onClick={() => void reload()}>Try again</button></div></div>}
        {view === 'month' && <MonthCalendar date={date} tutor={tutor} student={student} revision={calendarRevision} onSelect={day => { setDate(day); setView('week'); }} />}
        {view === 'week' && <>
        {!loadError && data && issues > 0 && <div className="issues-banner"><AlertTriangle size={17} /><span><strong>{issues} scheduling {issues === 1 ? 'issue' : 'issues'}</strong></span></div>}
        {loading && !data ? <div className="empty-state" role="status"><RefreshCw className="spin" size={24} /><h2>Loading schedule…</h2></div> : !loadError && !visible.length ? <div className="empty-state"><CalendarDays size={30} /><h2>{tutor || student ? 'No matching sessions' : 'No sessions scheduled'}</h2>{(tutor || student) && <p>Try another filter.</p>}{!(tutor || student) && <button className="button primary" disabled={!canWrite} onClick={() => setEditor({})}><Plus size={16} />Add the first session</button>}</div> : data && <><div className="table-wrap"><table><thead><tr><th>Time</th><th>Students</th><th>Tutor</th><th>Room</th><th>Status</th><th>Warnings</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{visible.map(s => <tr key={s.id}><td className="time-cell"><strong>{s.startTime}–{endTime(s)}</strong><small>{s.durationMin} min</small></td><td>{students(s)}</td><td><span className="tutor-name">{s.tutorName}</span><small>{data.tutors.find(t => t.id === s.tutorId)?.subject}</small></td><td><span className="room-label">{s.roomId}</span></td><td>{s.mode === 'pair' ? <span className="pair-summary">{s.bookings.filter(b => b.status === 'booked').length} booked{s.bookings.some(b => b.status === 'cancelled') && <small>{s.bookings.filter(b => b.status === 'cancelled').length} cancelled</small>}{s.bookings.some(b => b.status === 'no_show') && <small>{s.bookings.filter(b => b.status === 'no_show').length} no-show</small>}</span> : <Status status={s.bookings[0]?.status ?? 'cancelled'} />}</td><td><Warnings warnings={data.warnings.filter(w => w.sessionIds.includes(s.id))} /></td><td>{editButton(s)}</td></tr>)}</tbody></table></div><div className="mobile-sessions">{visible.map(s => <article className="mobile-session" key={s.id}><div className="mobile-session-top"><strong>{s.startTime}–{endTime(s)}<small>{s.durationMin} min</small></strong>{s.mode !== 'pair' && <Status status={s.bookings[0]?.status ?? 'cancelled'} />}</div>{students(s)}<div className="mobile-resources"><span><small>Tutor</small>{s.tutorName}</span><span><small>Room</small>{s.roomId}</span></div><div className="mobile-session-bottom"><Warnings warnings={data.warnings.filter(w => w.sessionIds.includes(s.id))} />{editButton(s)}</div></article>)}</div></>}
        </>}
        </section>
      {view === 'week' && <details className="history-panel"><summary><span><History size={18} /><strong>Changes for this day</strong><span className="count-badge">{data?.changes.length ?? 0}</span></span><ChevronDown size={18} /></summary><div className="history-body">{data?.changes.length ? data.changes.map(c => <Change key={c.id} change={c} date={date} />) : <p className="history-empty">No changes recorded.</p>}</div></details>}
      
    </main>{editor && data && <SessionDialog key={editor.session?.id ?? `new-${date}`} data={data} date={date} session={editor.session} onClose={() => setEditor(null)} onSaved={saved} onReload={reload} />}{cancelling && <CancelDialog {...cancelling} onClose={() => setCancelling(null)} onSaved={saved} onReload={reload} />}</>;
}

function Dialog({ title, children, onClose, busy }: { title: string; children: ReactNode; onClose: () => void; busy: boolean }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const dialog = ref.current; const trigger = document.activeElement as HTMLElement | null; dialog?.showModal(); return () => { dialog?.close(); trigger?.focus(); }; }, []);
  return <dialog ref={ref} className="modal" onCancel={e => { e.preventDefault(); if (!busy) onClose(); }} aria-labelledby="dialog-title"><div className="modal-header"><div><h2 id="dialog-title">{title}</h2></div><button className="button icon" disabled={busy} aria-label="Close dialog" onClick={onClose}><X size={19} /></button></div>{children}</dialog>;
}
function ErrorSummary({ error }: { error: ApiError | null }) { const ref = useRef<HTMLDivElement>(null); useEffect(() => { if (error) ref.current?.focus(); }, [error]); return error ? <div ref={ref} tabIndex={-1} className="form-error" role="alert"><strong>{error.code === 'UNKNOWN_OUTCOME' ? 'Save status unknown' : 'Cannot save this change'}</strong><p>{error.message}</p>{error.conflicts?.map((c, i) => <p key={i}>{c.message}</p>)}</div> : null; }
function useMutation(onSaved: () => Promise<void>) {
  const [pending, setPending] = useState(false); const [error, setError] = useState<ApiError | null>(null); const [uncertain, setUncertain] = useState(false);
  async function submit(url: string, method: string, body: unknown) {
    if (pending || uncertain) return;
    setPending(true); setError(null);
    try {
      const response = await fetch(url, { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
      let result: { error?: ApiError }; try { result = await response.json(); } catch { throw new Error('The server response could not be confirmed.'); }
      if (!response.ok) { if (response.status >= 500) throw new Error('The server could not confirm the result.'); setError(result.error ?? { code: 'SAVE_FAILED', message: 'The request was rejected. Check your draft and try again.' }); return; }
      await onSaved();
    } catch { setUncertain(true); setError({ code: 'UNKNOWN_OUTCOME', message: 'The connection ended before confirmation. This change may already be saved. Reload the latest schedule and review it before making another change.' }); }
    finally { setPending(false); }
  }
  return { pending, error, uncertain, submit };
}
function SessionDialog({ data, date, session, onClose, onSaved, onReload }: { data: ScheduleData; date: string; session?: Session; onClose: () => void; onSaved: () => Promise<void>; onReload: (targetDate?: string) => Promise<boolean> }) {
  const initial: SessionInput = { date: session?.date ?? date, startTime: session?.startTime ?? '09:00', durationMin: (session?.durationMin ?? 60) as 60 | 90, tutorId: session?.tutorId ?? '', roomId: session?.roomId ?? '', mode: session?.mode ?? 'one_to_one', studentIds: session?.bookings.map(b => b.studentId) ?? ['', ''], reason: '' };
  const submittedDate = useRef(initial.date); const [draft, setDraft] = useState(initial); const [discard, setDiscard] = useState(false); const [reloading, setReloading] = useState(false); const mutation = useMutation(onSaved);
  const update = <K extends keyof SessionInput>(key: K, value: SessionInput[K]) => setDraft(d => ({ ...d, [key]: value }));
  const close = () => { if (mutation.pending || reloading) return; if (mutation.uncertain) { void reloadLatest(); return; } if (JSON.stringify(draft) !== JSON.stringify(initial) && !discard) setDiscard(true); else onClose(); };
  const fieldError = (field: string) => mutation.error?.fieldErrors?.[field]?.map((message, i) => <span className="field-error" key={i}>{message}</span>);
  const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); if (session && !draft.reason?.trim()) { const input = e.currentTarget.querySelector('textarea'); input?.setCustomValidity('Enter a reason for this change, not only spaces.'); input?.reportValidity(); return; } const body = session ? { date: draft.date, startTime: draft.startTime, durationMin: draft.durationMin, tutorId: draft.tutorId, roomId: draft.roomId, reason: draft.reason?.trim(), expectedVersion: session.version } : { ...draft, reason: draft.reason?.trim(), studentIds: draft.studentIds.slice(0, draft.mode === 'pair' ? 2 : 1) }; submittedDate.current = draft.date; void mutation.submit(session ? `/api/sessions/${session.id}` : '/api/sessions', session ? 'PATCH' : 'POST', body); };
  const reloadLatest = async () => { setReloading(true); if (await onReload(mutation.uncertain ? submittedDate.current : session?.date ?? date)) onClose(); setReloading(false); };
  return <Dialog title={session ? 'Edit session' : 'Add a session'} onClose={close} busy={mutation.pending || reloading}><form onSubmit={submit}><div className="modal-body"><ErrorSummary error={mutation.error} />{(mutation.uncertain || mutation.error?.code.includes('STALE')) && <button type="button" className="button secondary" disabled={reloading} onClick={() => void reloadLatest()}><RefreshCw size={15} />{reloading ? 'Reloading…' : 'Load latest schedule and close draft'}</button>}
      {session ? <div className="info-box"><Users size={17} /><div><strong>{session.bookings.map(b => b.studentName).join(' & ')}</strong><p>This changes the shared session for {session.bookings.length} {session.bookings.length === 1 ? 'student' : 'students'}. Student selection is fixed.</p>{session.bookings.map(b => <p key={b.id}>{b.sourceLessonId && <span>{b.sourceLessonId} · </span>}{b.sourceNote || statusLabel(b.status)}</p>)}</div></div> : <><fieldset className="mode-field"><legend>Session type</legend><div className="mode-options">{(['one_to_one', 'pair'] as const).map(mode => <label key={mode} className={draft.mode === mode ? 'selected' : ''}><input type="radio" name="mode" checked={draft.mode === mode} onChange={() => update('mode', mode)} />{mode === 'pair' ? 'Pair · 2 students' : 'One-to-one'}</label>)}</div></fieldset><div className="form-grid">{Array.from({ length: draft.mode === 'pair' ? 2 : 1 }, (_, i) => <label className={draft.mode === 'one_to_one' ? 'full' : ''} key={i}>{draft.mode === 'pair' ? `Student ${i + 1}` : 'Student'}<select required value={draft.studentIds[i] ?? ''} onChange={e => { const ids = [...draft.studentIds]; ids[i] = e.target.value; update('studentIds', ids); }}><option value="">Select a student</option>{data.students.map(s => <option key={s.id} value={s.id} disabled={draft.mode === 'pair' && draft.studentIds[1 - i] === s.id}>{s.name}</option>)}</select>{fieldError('studentIds')}</label>)}</div></>}
      <div className="form-grid"><label className="full">Date<input type="date" required value={draft.date} onChange={e => update('date', e.target.value)} />{fieldError('date')}</label><label>Start time<input type="time" required value={draft.startTime} onChange={e => update('startTime', e.target.value)} />{fieldError('startTime')}</label><label>Duration<select value={draft.durationMin} onChange={e => update('durationMin', Number(e.target.value) as 60 | 90)}><option value={60}>60 minutes</option><option value={90}>90 minutes</option></select>{fieldError('durationMin')}</label><label>Tutor<select required value={draft.tutorId} onChange={e => update('tutorId', e.target.value)}><option value="">Select a tutor</option>{data.tutors.map(t => <option key={t.id} value={t.id}>{t.name} · {t.subject}</option>)}</select>{fieldError('tutorId')}</label><label>Room<select required value={draft.roomId} onChange={e => update('roomId', e.target.value)}><option value="">Select a room</option>{data.rooms.map(r => <option key={r.id} value={r.id}>{r.id}</option>)}</select>{fieldError('roomId')}</label><label className="full">{session ? 'Reason for change' : 'Note (optional)'}<textarea rows={2} required={!!session} maxLength={500} placeholder={session ? 'Help the next person understand this change.' : 'Anything reception should know?'} value={draft.reason} onChange={e => { e.target.setCustomValidity(session && !e.target.value.trim() ? 'Enter a reason for this change, not only spaces.' : ''); update('reason', e.target.value); }} />{fieldError('reason')}</label></div>{discard && <div className="discard-confirm" role="alert"><strong>Discard your unsaved changes?</strong><div><button type="button" className="button secondary" onClick={() => setDiscard(false)}>Keep editing</button><button type="button" className="button danger" onClick={onClose}>Discard draft</button></div></div>}</div><div className="modal-footer"><button type="button" className="button secondary" disabled={mutation.pending} onClick={close}>Cancel</button><button className="button primary" disabled={mutation.pending || mutation.uncertain || reloading}>{mutation.pending ? 'Saving…' : session ? 'Save changes' : 'Create session'}<ArrowUpRight size={16} /></button></div></form></Dialog>;
}
function CancelDialog({ session, booking, onClose, onSaved, onReload }: { session: Session; booking: Booking; onClose: () => void; onSaved: () => Promise<void>; onReload: (targetDate?: string) => Promise<boolean> }) {
  const [reason, setReason] = useState(''); const [discard, setDiscard] = useState(false); const [reloading, setReloading] = useState(false); const mutation = useMutation(onSaved); const remaining = session.bookings.filter(b => b.id !== booking.id && b.status !== 'cancelled');
  const close = () => { if (reloading) return; if (mutation.uncertain) { setReloading(true); void onReload().then(ok => { if (ok) onClose(); }).finally(() => setReloading(false)); return; } if (!mutation.pending) { if (reason && !discard) setDiscard(true); else onClose(); } };
  return <Dialog title="Cancel booking?" onClose={close} busy={mutation.pending || reloading}><form onSubmit={e => { e.preventDefault(); if (!reason.trim()) { const input = e.currentTarget.querySelector('textarea'); input?.setCustomValidity('Enter a cancellation reason, not only spaces.'); input?.reportValidity(); return; } void mutation.submit(`/api/bookings/${booking.id}/cancel`, 'POST', { expectedVersion: session.version, reason: reason.trim() }); }}><div className="modal-body"><ErrorSummary error={mutation.error} />{(mutation.uncertain || mutation.error?.code.includes('STALE')) && <button className="button secondary" type="button" disabled={reloading} onClick={async () => { setReloading(true); if (await onReload()) onClose(); setReloading(false); }}>{reloading ? 'Reloading…' : 'Load latest schedule and close draft'}</button>}<div className="cancel-overview"><strong>{booking.studentName}</strong><span>{formatDay(session.date)} · {session.startTime}–{endTime(session)}</span><span>{session.tutorName} · {session.roomId}</span></div><div className="info-box"><Users size={17} /><p>{remaining.length ? `${remaining.map(b => b.studentName).join(', ')} remains booked. The tutor and room stay reserved.` : 'This is the last active booking. Cancelling releases the tutor and room.'}</p></div><label className="field">Reason for cancellation<textarea autoFocus required rows={3} maxLength={500} value={reason} onChange={e => { e.target.setCustomValidity(!e.target.value.trim() ? 'Enter a cancellation reason, not only spaces.' : ''); setReason(e.target.value); }} placeholder="Explain why this booking is being cancelled." />{mutation.error?.fieldErrors?.reason?.map((message, i) => <span className="field-error" key={i}>{message}</span>)}</label>{discard && <div className="discard-confirm"><strong>Discard your cancellation draft?</strong><div><button type="button" className="button secondary" onClick={() => setDiscard(false)}>Keep editing</button><button type="button" className="button danger" onClick={onClose}>Discard draft</button></div></div>}</div><div className="modal-footer"><button type="button" className="button secondary" disabled={mutation.pending} onClick={close}>Keep booking</button><button className="button danger" disabled={mutation.pending || mutation.uncertain || reloading}>{mutation.pending ? 'Cancelling…' : 'Cancel booking'}</button></div></form></Dialog>;
}
